-- Indexed from: X:\Projects\Roblox Repos\Trade Cases Tutorial\src\ReplicatedStorage\Controllers\InterfaceController\InterfaceHandlers

export type ModuleNames = "HudInterface" | "InfoCardInterface" | "Template" | "WelcomeInterface"
export type Modules = (("HudInterface") -> (typeof(require(game.ReplicatedStorage.Controllers.InterfaceController.InterfaceHandlers.HudInterface)))) & (("InfoCardInterface") -> (typeof(require(game.ReplicatedStorage.Controllers.InterfaceController.InterfaceHandlers.InfoCardInterface)))) & (("Template") -> (typeof(require(game.ReplicatedStorage.Controllers.InterfaceController.InterfaceHandlers.Template)))) & (("WelcomeInterface") -> (typeof(require(game.ReplicatedStorage.Controllers.InterfaceController.InterfaceHandlers.WelcomeInterface))))

return {}
