--[[
    Written by MarkoGasta2 @ Studio Blackout
]]--

-- Type checking flags:
--!strict

local TemplateController = {}
function TemplateController.Init()

    --// SERVICES \\--

    --// CONFIG \\--

    --// MODULES \\--

    --// TYPES \\--

    --// CONSTANTS \\--

    --// VARIABLES \\--

    --// FUNCTIONS \\--

    warn(`Template initialized!`)

    --// EXPORTS \\--

end

return TemplateController